python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
    - method: pip
      path: pandas
    - method: pip
      path: numpy
    - method: pip
      path: Historic-Crypto