sphinx:
   configuration: docs/conf.py

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: numpy
    - method: pip
      path: pandas
    - method: pip
      path: Historic-Crypto
    - method: pip
      path: gym
    - method: pip
      path: ../.
